### PR TITLE
Deprecated methods updated in SVGExporter

### PR DESCRIPTION
**Pull request by dbtek**
Deprecated DisplayObject.getStage(), Container.getNumChildren(), Graphics.getInstructions() methods replaced with alternatives.

### CODE REVIEW

**Comment by lannymcnie** [comment]
I manually made this change because the pull request had a ton of unnecessary whitespace changes (auto-format?). Thanks for pointing it out, and I definitely don't want to encourage pull requests in the future :)

**Comment by gskinner** [comment]
Discourage. Lanny definitely doesn't want to DISCOURAGE pull requests. :)

**Comment by lannymcnie** [comment]
Yes, that is what I meant! Thanks @gskinner

**Comment by dbtek** [comment]
It's auto-format, not me :) Are whitespaces there for common style?

Want me to reopen without formatting?

**Pull request closed without merging**
