### PR TITLE
SpriteStage > root-level kids now take the stage's transform into account.

### PR DESCRIPTION
**Pull request by trevordunn**
Addresses issue https://github.com/CreateJS/EaselJS/issues/670
Replaces PR https://github.com/CreateJS/EaselJS/pull/671

### CODE REVIEW

**Comment by eirikurn** [comment]
Hey! Any info on when this PR will land? This issue is breaking the responsive (scaled) rendering in my app.

**Comment by ndevr** [comment]
Can this pull request be accepted?

**Comment by lannymcnie** [comment]
Not sure this PR will get accepted, as a new WebGL implementation is currently in beta: https://github.com/CreateJS/EaselJS/tree/StageGL-beta

**Comment by gskinner** [comment]
We should double check that the new implementation does handle this scenario correctly.

**Comment by DavidHGillen** [comment]
Checking into this took a little time but I can confirm the StageGL branch supports the above functionality currently without need for changes.

**Pull request closed without merging**
