### PR TITLE
Add support for non breaking spaces

### PR DESCRIPTION
**Pull request by daedeloth**
Hi

I've changed the way words are split in Text elements so that it respects non breaking spaces.
I feel like this should be the default way of handling this, so that's why I'm submitting this pull requests :-)

Thanks for your consideration

Thijs

### CODE REVIEW

**Review by danzen — CHANGES_REQUESTED** [review]
Sounds like a good idea but when I add the private method it does not work for me.  If, in the method, I replace 

return str.split(/(\f\n\r\t\v\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff)/);

with 

return str.split(/(\s)/);

then it does  work.  Weird - on latest Chrome, Firefox and Edge - Win 10.

**Comment by daedeloth** [comment]
Hi

This sounds very strange, I have a build of this at https://github.com/CatLabInteractive/EaselJS/tree/catlab-build and I'm already using this in our project at beta.quizwitz.com, so not sure why it wouldn't work? What is the error you are seeing?

Thanks
Thijs

**Comment by daedeloth** [comment]
Sorry, you are correct, it is not working at the moment. I'll see if I can fix it.

**Comment by daedeloth** [comment]
Sorry about this, it wasn't properly tested and I incorrectly copied the regular expression from https://developer.mozilla.org/nl/docs/Web/JavaScript/Guide/Regular_Expressions. Now it should be correct.

**Comment by danzen** [comment]
This was put in place without the Merge... not sure why but it was there when I looked.

**Pull request closed without merging**
